// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject.Data;

#nullable disable

namespace MyProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("MyProject.Data.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ManagementGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ManagementGroupId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("MyProject.Data.Models.AssignmentClassificationConstraint", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBalanceOrSeparation")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentId", "ClassificationId");

                    b.HasIndex("ClassificationId");

                    b.ToTable("AssignmentClassificationConstraints");
                });

            modelBuilder.Entity("MyProject.Data.Models.AssignmentConflict", b =>
                {
                    b.Property<int>("AssignmentConflictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemRecommendation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentConflictId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignmentConflicts");
                });

            modelBuilder.Entity("MyProject.Data.Models.AssignmentScoreBreakdown", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BalancePenalty")
                        .HasColumnType("REAL");

                    b.Property<double>("FinalSigma")
                        .HasColumnType("REAL");

                    b.Property<double>("IsolationPenalty")
                        .HasColumnType("REAL");

                    b.Property<string>("ScoreExplanation")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<double>("SocialScore")
                        .HasColumnType("REAL");

                    b.HasKey("AssignmentId");

                    b.ToTable("AssignmentScoreBreakdowns");
                });

            modelBuilder.Entity("MyProject.Data.Models.BestSolutionArchive", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("BestScore")
                        .HasColumnType("REAL");

                    b.Property<string>("SolutionStateBlob")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasDiversified")
                        .HasColumnType("INTEGER");

                    b.HasKey("RunId");

                    b.ToTable("BestSolutionArchives");
                });

            modelBuilder.Entity("MyProject.Data.Models.Classification", b =>
                {
                    b.Property<int>("ClassificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ClassificationId");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("MyProject.Data.Models.ClassificationAttribute", b =>
                {
                    b.Property<int>("ClassificationAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClassificationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClassificationAttributeId");

                    b.HasIndex("ClassificationId", "AttributeName")
                        .IsUnique();

                    b.ToTable("ClassificationAttributes");
                });

            modelBuilder.Entity("MyProject.Data.Models.GroupCountConstraint", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxGroups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinGroups")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentId");

                    b.ToTable("GroupCountConstraints");
                });

            modelBuilder.Entity("MyProject.Data.Models.GroupSizeConstraint", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxGroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinGroupSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentId", "GroupId");

                    b.ToTable("GroupSizeConstraints");
                });

            modelBuilder.Entity("MyProject.Data.Models.ManagementGroup", b =>
                {
                    b.Property<int>("ManagementGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagementGroupName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ManagementGroupId");

                    b.HasIndex("ManagerId");

                    b.ToTable("ManagementGroups");
                });

            modelBuilder.Entity("MyProject.Data.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ManagerId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("MyProject.Data.Models.MandatoryConstraint", b =>
                {
                    b.Property<int>("MandatoryConstraintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConstraintName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.HasKey("MandatoryConstraintId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("MandatoryConstraints");
                });

            modelBuilder.Entity("MyProject.Data.Models.MandatoryConstraintAssignment", b =>
                {
                    b.Property<int>("MandatoryConstraintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantAssignmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MandatoryConstraintId", "ParticipantAssignmentId");

                    b.HasIndex("ParticipantAssignmentId");

                    b.ToTable("MandatoryConstraintAssignments");
                });

            modelBuilder.Entity("MyProject.Data.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsraeliIdentityNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantId");

                    b.HasIndex("IsraeliIdentityNumber")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("MyProject.Data.Models.ParticipantAssignment", b =>
                {
                    b.Property<int>("ParticipantAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BalanceContribution")
                        .HasColumnType("REAL");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipantAssignmentId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ParticipantAssignments");
                });

            modelBuilder.Entity("MyProject.Data.Models.ParticipantClassification", b =>
                {
                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassificationAttributeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipantId", "ClassificationAttributeId");

                    b.HasIndex("ClassificationAttributeId");

                    b.ToTable("ParticipantClassifications");
                });

            modelBuilder.Entity("MyProject.Data.Models.SocialPreference", b =>
                {
                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromParticipantAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToParticipantAssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferenceWeight")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignmentId", "FromParticipantAssignmentId", "ToParticipantAssignmentId");

                    b.HasIndex("FromParticipantAssignmentId");

                    b.HasIndex("ToParticipantAssignmentId");

                    b.ToTable("SocialPreferences");
                });

            modelBuilder.Entity("MyProject.Data.Models.Assignment", b =>
                {
                    b.HasOne("MyProject.Data.Models.ManagementGroup", null)
                        .WithMany()
                        .HasForeignKey("ManagementGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.AssignmentClassificationConstraint", b =>
                {
                    b.HasOne("MyProject.Data.Models.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.Data.Models.Classification", null)
                        .WithMany()
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.AssignmentConflict", b =>
                {
                    b.HasOne("MyProject.Data.Models.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.AssignmentScoreBreakdown", b =>
                {
                    b.HasOne("MyProject.Data.Models.Assignment", null)
                        .WithOne()
                        .HasForeignKey("MyProject.Data.Models.AssignmentScoreBreakdown", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.ClassificationAttribute", b =>
                {
                    b.HasOne("MyProject.Data.Models.Classification", null)
                        .WithMany()
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.GroupCountConstraint", b =>
                {
                    b.HasOne("MyProject.Data.Models.Assignment", null)
                        .WithOne()
                        .HasForeignKey("MyProject.Data.Models.GroupCountConstraint", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.GroupSizeConstraint", b =>
                {
                    b.HasOne("MyProject.Data.Models.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.ManagementGroup", b =>
                {
                    b.HasOne("MyProject.Data.Models.Manager", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.MandatoryConstraint", b =>
                {
                    b.HasOne("MyProject.Data.Models.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.MandatoryConstraintAssignment", b =>
                {
                    b.HasOne("MyProject.Data.Models.MandatoryConstraint", null)
                        .WithMany()
                        .HasForeignKey("MandatoryConstraintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.Data.Models.ParticipantAssignment", null)
                        .WithMany()
                        .HasForeignKey("ParticipantAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.ParticipantAssignment", b =>
                {
                    b.HasOne("MyProject.Data.Models.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.Data.Models.Manager", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyProject.Data.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.ParticipantClassification", b =>
                {
                    b.HasOne("MyProject.Data.Models.ClassificationAttribute", null)
                        .WithMany()
                        .HasForeignKey("ClassificationAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyProject.Data.Models.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyProject.Data.Models.SocialPreference", b =>
                {
                    b.HasOne("MyProject.Data.Models.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyProject.Data.Models.ParticipantAssignment", "FromParticipantAssignment")
                        .WithMany()
                        .HasForeignKey("FromParticipantAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyProject.Data.Models.ParticipantAssignment", "ToParticipantAssignment")
                        .WithMany()
                        .HasForeignKey("ToParticipantAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("FromParticipantAssignment");

                    b.Navigation("ToParticipantAssignment");
                });
#pragma warning restore 612, 618
        }
    }
}
